---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.html
  label: About
  match: "**/*"
- type: directory
  path: _locations
  label: Add Rail Locations
  create: documents
  match: "**/*"
  templates:
  - location
- type: heading
  label: Edit Site Text
- type: document
  path: _includes/header.html
  label: Header
- type: document
  path: _includes/locations.html
  label: Find
- type: document
  path: _includes/host.html
  label: Host
upload_dir: uploads
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
